### ISSUE TITLE
请教如何使用这个

### ISSUE THREAD

**Issue by tiannian** [zanjie1999/httpRandomMusic#1]
关于这个项目的一些问题想请教一下：
 
1. README中提到的小怪是您自己编写的服务么？我没有找到相关的服务接入方法，或者是相关的repo.
2. 另外一个是想请教一下，小爱音响是否支持dlna？

**Comment by zanjie1999** [comment]
1自己写的，repo是私仓，不开源
2只有超贵那几款支持，其他不支持
怎么用看md，你不需要理解他怎么实现的，只需要照着md做
