### ISSUE TITLE
用电脑浏览器可以访问zyym.ie:65533了，但是小爱音箱尝试失败，不知道方法哪里错了

### ISSUE THREAD

**Issue by chunbo129** [zanjie1999/httpRandomMusic#11]

**Comment by zanjie1999** [comment]
说明你没弄好dns劫持，注意是要劫持局域网所有的dns流量

**Comment by chunbo129** [comment]
经过各种折腾终于成功了，还是来这里回复一下。
感谢共享这个项目，还是很实用的，必须点赞支持。
另外，分享一个小经验。我是在openwrt上运行的，包括dns劫持也是，问题出在了我以为修改hosts之后重启路由器就可以了，但实际上重启路由器没啥用，直到最后重启dnsmasq服务才成功了。
