### ISSUE TITLE
布署是成功了，但本地浏览器上测试时直接下载文件了

### ISSUE THREAD

**Issue by brainpeng** [zanjie1999/httpRandomMusic#12]

**Comment by brainpeng** [comment]
不会出现播放器窗口

**Comment by brainpeng** [comment]
![image](https://github.com/zanjie1999/httpRandomMusic/assets/8011623/6786c91e-fc53-4633-b33b-fd419595cea6)

**Comment by zanjie1999** [comment]
带IDM插件是这样的，所以我不装这个傻逼插件
