### ISSUE TITLE
群晖 执行python3 xxx 报错 SyntaxError: invalid syntax。

### ISSUE THREAD

**Issue by android-zhaoyongtao** [zanjie1999/httpRandomMusic#13]
➜  ~ python3 /Users/zhaoyongtao/Downloads/httpRandomMusic.py
  File "/Users/zhaoyongtao/Downloads/httpRandomMusic.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
<img width="492" alt="image" src="https://github.com/zanjie1999/httpRandomMusic/assets/18624444/05f8a77d-5f1f-4d29-aedb-189c9b3e6682">
![image](https://github.com/zanjie1999/httpRandomMusic/assets/18624444/b7da7613-8b07-4709-98ab-5f3d99a5db7d)

**Comment by lzg134679** [comment]
先用ssh软件连上，直接命令行运行脚本试试
如果没问题，那应该是群晖的任务有问题
群晖的定时任务一般是用sh脚本去执行
下面是我能运行的例子

1.在任意位置创建一个music-to-xiaoai.sh脚本（最好在py脚本同目录下创建）
脚本内容：
#!/bin/bash
PYTHON_SCRIPT="/var/lib/httprandommusic/httpRandomMusic.py"    # 你的Python脚本路径，要绝对路径，同目录下可以用相对路径
python3 $PYTHON_SCRIPT

2.群晖网页上控制面板-任务计划-新建-触发的任务-用户自定义脚本
任务名称随便填，用户账号root，事件开机
切到任务设置，脚本里填：bash /volume1/sh/music-to-xiaoai.sh    # 你的sh脚本路径
创建好之后运行就行

**Comment by zanjie1999** [comment]
希望大家等都能学会如何提问


![image](https://github.com/zanjie1999/httpRandomMusic/assets/16502567/4b7dc68d-c11d-42ca-91d3-fa8198f8342e)


![image](https://github.com/zanjie1999/httpRandomMusic/assets/16502567/f362541a-1c08-46b8-bbc6-f95d665a266e)

**Comment by android-zhaoyongtao** [comment]
不好意思，前几天没学会截图。这个电脑不常用，现在补充的很详细，可以帮看看吗？
我的 python水平也就菜鸟教程。只会 python 语法，写 200 行以内的脚本。。。

**Comment by android-zhaoyongtao** [comment]
> 不好意思，前几天没学会截图。这个电脑不常用，现在补充的很详细，可以再帮看看吗？

**Comment by zanjie1999** [comment]
你要下载我的文件，而不是随便找一个文件改成这个名字就行

你自己看我的文件第7行是什么

**Comment by android-zhaoyongtao** [comment]
> 你要下载我的文件，而不是随便找一个文件改成这个名字就行
> 
> 你自己看我的文件第7行是什么

OK。get了。可能是把html下载下来了
