### ISSUE TITLE
群晖下使用计划任务，python /脚本路径 运行，播放的次数多了之后会无法播放。

### ISSUE THREAD

**Issue by mulaxiusi** [zanjie1999/httpRandomMusic#15]
尝试了不是小爱音箱的问题，两个不同型号的小爱音箱都不能播放，重启计划任务或者重启python，换python版本都无法解决。只有重启群晖，就能使用。播放个几十次后，就会变得无法播放，触屏音箱显示音乐是有推送的，但是无法播放。是不是缓存之类的？请问能解决么？在网上找其他方案，感觉还是博主这个比较简单好用

**Comment by zanjie1999** [comment]
正常，有运行时长限制，写计划任务里的话，用nohup就行
