### ISSUE TITLE
“播放失败，请检查网络，或换一个试试吧”

### ISSUE THREAD

**Issue by rendaa** [zanjie1999/httpRandomMusic#3]
已按README.md中的要求正确配置了 fileDir 变量、以及在域名解析中添加 op.lan 记录。

py文件和音乐文件都是放置在NAS上的，用对音乐文件目录有rwx访问权限的用户启动 python3 httpRandomMusic.py &（为方便这里用了后台运行），启动后显示 "208 files" 这样的信息（和目录中音乐文件数量相同，音乐文件绝大多数都是mp3的，在其它设备上都可正常播放）。

在NAS上ping op.lan，可以正确解析op.lan为NAS自己的IP。

在NAS上用 netstat -anp | grep python3 可以看到以下端口：
tcp        0      0 0.0.0.0:65533           0.0.0.0:*               LISTEN      19439/python3       
tcp        0      0 127.0.0.1:5555          0.0.0.0:*               LISTEN      32152/python3       
tcp        0      0 127.0.0.1:33300         0.0.0.0:*               LISTEN      17432/python3       
unix  3      [ ]         STREAM     CONNECTED     224309   32152/python3        
unix  2      [ ]         DGRAM                    283491   17432/python3        
unix  2      [ ]         DGRAM                    283563   17432/python3        
unix  2      [ ]         DGRAM                    213795   32152/python3        
unix  3      [ ]         STREAM     CONNECTED     180874   32152/python3        
unix  3      [ ]         STREAM     CONNECTED     224308   32152/python3        
unix  3      [ ]         STREAM     CONNECTED     283955   17432/python3

对小爱音箱说“小爱同学，打开小怪”，音箱回应“开始咯”，嘟声后继续说“播放服务器上的音乐”，音箱回应“即将播放艾福杰尼的《看上去像个Rap Star》”并开始放歌……但我奇怪的是我的音乐目录里并没有这歌。

对小爱音箱说“小爱同学，打开小怪”，音箱回应“开始咯”，嘟声后继续说“从头播放服务器的音乐”，音箱回应“好菜”，然后没有声音了，过一会儿音箱会说“播放失败，请检查网络，或换一个试试吧”。

对小爱音箱说“小爱同学，打开小怪”，音箱回应“开始咯”，嘟声后继续说“随机播放服务器的音乐”，音箱回应“好菜”，然后没有声音了，过一会儿音箱会说“播放失败，请检查网络，或换一个试试吧”。

可否帮助指引一下可能是哪里出现问题了？

P.S. 小爱音箱是多年前最早一批发售的，不知和这个问题有没有关系。

**Comment by zanjie1999** [comment]
首先，是“播放服务器的音乐”不是“播放服务器上的音乐”，所以命中的是去网易云搜索“服务器上的音乐”的第一首来播放
另外两个问题看一下米家里的（必须是米家里的才会完整显示）音响的对话记录，看看都识别成了什么，回应好菜是因为没有没有命中任何功能，必须只字不差，因为我没有保存任何日志，所以也查不到具体识别到了什么，这个得你自己查对话记录 XD
因为给音响提供音乐文件的是本地的服务器，返回内容的是云端服务器，这两个服务器并不会有任何通讯，所以音响是完全不知道他放的是什么的，如果连不上本地的服务器，会一直提示播放失败（Openwrt音响），或者完全没声音（NuttX音响）

**Comment by rendaa** [comment]
感谢您及时的回复！

对于第一个问题，谢谢提醒，已注意到那两个命令中相差的那个“上”字。因此这个问题请略过。

关于后两个问题，查阅了米家app里那个音箱的对话记录，语音命令识别没有问题，但对话记录中音箱的回应显示的是“音频”二字，这之后过一会儿能听到播放失败，请检查网络或换一个试试吧”的语音。

程序运行时使用其它设备尝试telnet到NAS的65533口，可以连接上，不知是否只使用了这个端口。

以上情况供您参考。目前我暂时先不继续玩这个功能了，您可不必过多花费时间回复此消息了（我就顺手把此issue关闭了）。

再次感谢您！

**Comment by zanjie1999** [comment]
1 音频是正确的
2 听到播放失败是因为连不上，你需要在路由器的host将op解析到你的服务器，让局域网的设备去路由器问dns时可以拿到你的服务端ip，说复杂点，你得设置路由器的iptables将出站udp53劫持到路由器本身解析，说简单点，将服务器主机名改成op就行
3 如果连接成功，可以在py程序上看到输出，只用到这一个端口，可以直接用浏览器访问测试

**Comment by rendaa** [comment]
如本issue最早的thread开头所述，之前已经进行过设置，将op.lan解析为NAS的局域网地址，并且实际上在不同的设备上ping op.lan都可以看到ping的是NAS的IP。

后来的尝试这点没有改变，op.lan仍然指向NAS的IPv4地址。

此外，也添加了op的项，也解析为NAS的IPv4地址。就是说，在各个设备上ping op.lan、以及ping op，都可以看到来自NAS的IPv4那个地址的回应。

但接下来的测试音箱还是回应“播放失败，请检查网络或换一个试试吧”。

然而在其它设备（目前我用的是手头回复您使用的iPad）上用浏览器访问http://op.lan:65533 ，可以看到一个播放器界面，点击播放按钮能够播放出那个目录里的音乐。播放音乐的时候点地址栏，会看到URL变成了例如 “op.lan:65533/柳爽%20-%20漠河舞厅·2022.mp3”这样的内容。

又试了一下浏览器访问http://op:65533 ，也能够播放那个目录的其它音乐（这次没等我点按钮，直接自动放出声音了，也可能前一次我没注意它没有加载完就点了按钮）。这次地址栏内URL是“op:65533/Swan%20-%20Secret%20Garden.mp3”

无论如何，好像还是有点进展，似乎至少排除了网络和防火墙设置等方面的问题？

P.S. 刚才播放歌曲的时候没注意看NAS那边的屏幕输出，现在补上刚才python3 http RandomMusic.py命令下面的输出：

```
#python3 httpRandomMusic.py 
208 files
/
192.168.8.66 - - [31/Jan/2023 22:29:43] "GET / HTTP/1.1" 302 -
/%E6%9F%B3%E7%88%BD%20-%20%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%C2%B72022.mp3
/volume1/RAID/_down/sd/柳爽 - 漠河舞厅·2022.mp3
192.168.8.66 - - [31/Jan/2023 22:29:43] "GET /%E6%9F%B3%E7%88%BD%20-%20%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%C2%B72022.mp3 HTTP/1.1" 200 -
/favicon.ico
/volume1/RAID/_down/sd/favicon.ico
192.168.8.66 - - [31/Jan/2023 22:29:44] "GET /favicon.ico HTTP/1.1" 404 -
/%E6%9F%B3%E7%88%BD%20-%20%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%C2%B72022.mp3
/volume1/RAID/_down/sd/柳爽 - 漠河舞厅·2022.mp3
192.168.8.66 - - [31/Jan/2023 22:30:02] "GET /%E6%9F%B3%E7%88%BD%20-%20%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%C2%B72022.mp3 HTTP/1.1" 200 -
/
192.168.8.66 - - [31/Jan/2023 23:00:00] "GET / HTTP/1.1" 302 -
/Swan%20-%20Secret%20Garden.mp3
/volume1/RAID/_down/sd/Swan - Secret Garden.mp3
192.168.8.66 - - [31/Jan/2023 23:00:00] "GET /Swan%20-%20Secret%20Garden.mp3 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.8.66', 59270)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "httpRandomMusic.py", line 82, in do_GET
    shutil.copyfileobj(f, self.wfile)
  File "/usr/lib/python3.8/shutil.py", line 208, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.8/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
/Swan%20-%20Secret%20Garden.mp3
/volume1/RAID/_down/sd/Swan - Secret Garden.mp3
192.168.8.66 - - [31/Jan/2023 23:00:02] "GET /Swan%20-%20Secret%20Garden.mp3 HTTP/1.1" 200 -
/favicon.ico
/volume1/RAID/_down/sd/favicon.ico
192.168.8.66 - - [31/Jan/2023 23:00:02] "GET /favicon.ico HTTP/1.1" 404 -
/Swan%20-%20Secret%20Garden.mp3
/volume1/RAID/_down/sd/Swan - Secret Garden.mp3
192.168.8.66 - - [31/Jan/2023 23:00:32] "GET /Swan%20-%20Secret%20Garden.mp3 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.8.66', 59283)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "httpRandomMusic.py", line 82, in do_GET
    shutil.copyfileobj(f, self.wfile)
  File "/usr/lib/python3.8/shutil.py", line 208, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.8/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
/apple-touch-icon-152x152-precomposed.png
/volume1/RAID/_down/sd/apple-touch-icon-152x152-precomposed.png
192.168.8.66 - - [31/Jan/2023 23:00:33] "GET /apple-touch-icon-152x152-precomposed.png HTTP/1.1" 404 -
/apple-touch-icon-152x152.png
/volume1/RAID/_down/sd/apple-touch-icon-152x152.png
192.168.8.66 - - [31/Jan/2023 23:00:33] "GET /apple-touch-icon-152x152.png HTTP/1.1" 404 -
/apple-touch-icon-precomposed.png
/volume1/RAID/_down/sd/apple-touch-icon-precomposed.png
192.168.8.66 - - [31/Jan/2023 23:00:33] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 -
/apple-touch-icon.png
/volume1/RAID/_down/sd/apple-touch-icon.png
192.168.8.66 - - [31/Jan/2023 23:00:33] "GET /apple-touch-icon.png HTTP/1.1" 404 -
/favicon.ico
/volume1/RAID/_down/sd/favicon.ico
192.168.8.66 - - [31/Jan/2023 23:00:33] "GET /favicon.ico HTTP/1.1" 404 -
/apple-touch-icon-152x152-precomposed.png
/volume1/RAID/_down/sd/apple-touch-icon-152x152-precomposed.png
192.168.8.66 - - [31/Jan/2023 23:00:33] "GET /apple-touch-icon-152x152-precomposed.png HTTP/1.1" 404 -
/apple-touch-icon-152x152.png
/volume1/RAID/_down/sd/apple-touch-icon-152x152.png
192.168.8.66 - - [31/Jan/2023 23:00:33] "GET /apple-touch-icon-152x152.png HTTP/1.1" 404 -
/apple-touch-icon-precomposed.png
/volume1/RAID/_down/sd/apple-touch-icon-precomposed.png
192.168.8.66 - - [31/Jan/2023 23:00:33] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 -
/apple-touch-icon.png
/volume1/RAID/_down/sd/apple-touch-icon.png
192.168.8.66 - - [31/Jan/2023 23:00:33] "GET /apple-touch-icon.png HTTP/1.1" 404 -
/favicon.ico
/volume1/RAID/_down/sd/favicon.ico
192.168.8.66 - - [31/Jan/2023 23:00:33] "GET /favicon.ico HTTP/1.1" 404 -
```

其中192.168.8.66是我这个iPad。

**Comment by zanjie1999** [comment]
我当然知道你的其他设备能正确解析，但这一点用都没有，和小爱音响没有关系，你要做的是让小爱音响在op.lan解析到你的nas，你让音响播放的时候，nas有收到请求，这才叫成功
首先，音响重启过吗，udp53的出站dns请求劫持到路由器了吗？
音响并不一定会用你dhcp返回给他的dns来解析域名
openwrt路由劫持dns的iptables规则：
```
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
```
r如果你实在不知道怎么操作，改主机名吧，，应该行的，但请务必重启音响清理音响的dns缓存

**Comment by rendaa** [comment]
感谢指点！

我的路由器用的是FreshTomato固件，已开了WebAdmin UI中DHCP / DNS Server下的Intercept DNS port选项（但根据网页上的说明“`Intercept DNS port - Any DNS requests/packets sent out to UDP/TCP port 53 are redirected to the internal DNS server. Currently only IPv4 DNS is intercepted.`”，这个选项只劫持IPv4的到TCP53和UDP53口的请求）。

此外也用你的iptables和ip6tables贴过去（FreshTomato里那个表也是叫nat），把 -A 改成了 -I 以便让这些规则插在Chain的最前面，ipv4的两条执行没问题，ip6tables两条不行
```
Warning: Extension REDIRECT revision 0 not supported, missing kernel module?
ip6tables v1.8.8 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
```
试了一下insmod ip6table_nat说 insmod: 'ip6table_nat.ko': module not found……总之ipv6这个先不管了。

也把音箱重新加电了。

再试，还是老样子…………

现在我为难在怎么判断小爱音箱用UDP53解析那域名的请求是不是被劫持到路由器了，在路由器上用tcpdump试着抓port 53、以及host 小爱音箱的包，winshark里打开那些cap文件按字符串查找包，没有发现包含op.lan的内容（有音箱解析其它域名例如ot.io.mi.com、tracker.ai.xiaomi.com等域名的）。不过我的经验里在我那个路由器上抓WLAN连接的包经常有抓不到的所以也不一定就真没有。

改主机名这个我没试（怕改名/恢复操作涉及的东西一多影响现在在用的东西），此外有些没想明白，如果是觉得小爱走UDP53用外部DNS解析op.lan，好像改名也不能让外面那个DNS的op.lan指向我的NAS啊……如果改名起作用，那似乎把路由器上的解析弄对了也就可以了……

要不我还是暂时先不玩这个功能了。

真心感谢您那么多次的帮助和及时的回复、指点！！

**Comment by zanjie1999** [comment]
把音响断电重启，这样可以清空他的dns缓存

**Comment by rendaa** [comment]
之前试过重新加电了，但问题依旧……

**Comment by zanjie1999** [comment]
那我不知道了，还有一条路可以走，主机名改成op

**Comment by rendaa** [comment]
这几天在忙些别的，先暂时不试下去了。非常感谢您的帮助！

**Comment by openegg** [comment]
我也试过了，现象和rendaa的一模一样，而且我也改了主机名。我的也是最早一批的小米AI音箱。不知道zanjie1999用的是哪一款小爱音箱？很棒的project，希望能推广！

**Comment by zanjie1999** [comment]
@openegg 我这有两个，一个是play增强版（就那个用辣鸡bes2300的）一个红米的play（用全志跑openwrt的），这两个都没有问题，dns的话udp和tcp流量全由openwrt路由器劫持到路由本身了

有一说一，改了主机名还用不了这个有点离谱

**Comment by openegg** [comment]
我也有一个红米的play版小爱音箱。试过也不行。

**Comment by openegg** [comment]
我的路由器是老毛子（padavan）固件，你知道怎么设置dns劫持吗

**Comment by openegg** [comment]
![1676965486280](https://user-images.githubusercontent.com/47627030/220280284-256a70b7-d22a-4430-b19b-4d998f3e1c29.png)
是这个吗？我开了的呀

**Comment by zanjie1999** [comment]
@openegg 对，是这个，不知道小米有没有用tcp进行dns解析，可以抓包看看，至于究竟是文件真不能播放，还是连不上，可以看看服务端有没有输出被连接的log，实在不行改主机名

**Comment by zanjie1999** [comment]
将音响请求的域名从op改成了op.lan，这样在音响的dnsmasq也能自动的解析成局域网的主机名  
具体看看md
可以再试试

**Comment by wangrui1573** [comment]
我也有一个小米红外万能版小爱音箱。试过 改主机名，劫持53，该iptables 改也不行，一直回复 播放失败，好菜 好菜。。
查看对话，出来了一个你是谁？郝菜
<img width="1095" alt="image" src="https://github.com/zanjie1999/httpRandomMusic/assets/42831156/b533426c-4449-4b76-bf9e-450b9aeaab8d">

**Comment by zanjie1999** [comment]
@wangrui1573 
指令是“播放服务器的音乐”，必须一字不差
播放失败你得看Python那边有没有请求进来，有就是你实时转码的ffmpeg问题或者音频文件根本就不是mp3解码不了，没有进来就是dns劫持不到位

**Comment by wangrui1573** [comment]
> @wangrui1573 指令是“播放服务器的音乐”，必须一字不差 播放失败你得看Python那边有没有请求进来，有就是你实时转码的ffmpeg问题或者音频文件根本就不是mp3解码不了，没有进来就是dns劫持不到位

姐，能不能在小爱开发平台更新一下小怪，增加一个指令，播放本地歌曲，对应的请求url设置为IP，不在请求域名

比如 请求 http://192.168.31.192:65532/

至于每个人IP不一样的问题，我们挂个旁路由或者反向代理自行解决

**Comment by zanjie1999** [comment]
> > @wangrui1573 指令是“播放服务器的音乐”，必须一字不差 播放失败你得看Python那边有没有请求进来，有就是你实时转码的ffmpeg问题或者音频文件根本就不是mp3解码不了，没有进来就是dns劫持不到位
> 
> 姐，能不能在小爱开发平台更新一下小怪，增加一个指令，播放本地歌曲，对应的请求url设置为IP，不在请求域名
> 
> 比如 请求 http://192.168.31.192:65532/
> 
> 至于每个人IP不一样的问题，我们挂个旁路由或者反向代理自行解决

需求那么多让小米做去，我已经不再需要使用这个服务（小爱音响已经因为闹钟太拉没网不响已经出掉了，取而代之的则是[这个项目](https://github.com/zanjie1999/workdayAlarmClockAndroid)），现在跑着纯粹就是用爱发电，浪费资源（每天的压力大部分来自小米的自动压测），已经有停了的打算了，然后你们自己跑服务，自己实名提交给小米审核，自己使用

既然你都有旁路由了，怎么连个dns劫持都做不到？
补充：记得在路由器将tcp53和udp53都劫持到你的dns服务器，包括ipv6，如果使用openwrt作为主路由，则增加自定义防火墙规则
```
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
```

**Comment by wangrui1573** [comment]
你看下上面的贴图，路由下面其他设备劫持都实现了，就是小爱音箱本身不行，53端口也劫持了
放弃了 我自己用HACS方法试试

![image](https://github.com/zanjie1999/httpRandomMusic/assets/42831156/8417aa5c-0986-4799-9b27-ad5813537823)

**Comment by zanjie1999** [comment]
> 你看下上面的贴图，路由下面其他设备劫持都实现了，就是小爱音箱本身不行，53端口也劫持了 放弃了 我自己用HACS方法试试
> 
> ![image](https://user-images.githubusercontent.com/42831156/268811494-8417aa5c-0986-4799-9b27-ad5813537823.png)

我有个好建议，你吧路由的主机名改成op然后iptables写个端口转发过去你的nas

你在路由器上劫持，在路由器上测试，那就相当于我在我电脑上写了个hosts，然后在电脑上测是差不多的道理，没意义的

**Comment by wangrui1573** [comment]
恩恩，感谢，我怀疑问题可能出在IPV6，或者是clash 插件也有影响，我先试试，端口转发我觉得应该能成
另外不只是在路由上测试了，在路由下的PC 和群晖、armbian盒子测过也可以curl正常

顺便问下，[小米小爱开放平台](https://developers.xiaoai.mi.com/) 申请和审核严格吗？我准备试试写个试试

**Comment by zanjie1999** [comment]
> 恩恩，感谢，我怀疑问题可能出在IPV6，或者是clash 插件也有影响，我先试试，端口转发我觉得应该能成 另外不只是在路由上测试了，在路由下的PC 和群晖、armbian盒子测过也可以curl正常
> 
> 顺便问下，[小米小爱开放平台](https://developers.xiaoai.mi.com/) 申请和审核严格吗？我准备试试写个试试

审核比较严格，屁事很多，另外对延时和响应速度超级严格，目前是在国内租了云服务器才能满足他的需求

**Comment by zanjie1999** [comment]
劫持失败请在 路由器后台 -> 网络 ->DHCP/DNS-> 一般设置 -> 重绑定保护（丢弃 RFC1918 上行响应数据），把这个的勾去掉 保存应用

另外由于小爱的固件更新，导致.lan这个后缀解析不了了，因此换成了zyym.ie这个不存在的域名

**Comment by rendaa** [comment]
这次成功了，进来汇报一下。

刚刚用20240508的版本在N1盒子的armbian里试过（路由器hosts里加了zyym.ie解析并重启dnsmasq服务），终于可以正确播放了！

时隔那么久@zanjie1999还在坚持用爱发电，真的要谢谢你的爱~~
虽然在作者眼里这个功能可能很小，但真的很实用，对我来说很需要，谢谢！谢谢！谢谢！

顺便提个建议，既然每次都要先说“打开小怪”然后发这里那三条命令，能不能加几个简单版的命令别名、比如“随机播放”和“随机播放服务器的音乐”等效？一字不差地说那么长的命令有些违背人性…

另外要能给加个“下一首”、以便跳过当前的歌，就更方便了。

祝开心、愉快、多爱以供发电！

**Comment by rendaa** [comment]
刚才搜了一下，看到@wangrui1573的修改版本 https://github.com/wangrui1573/Xiaoai_PlayLocal ，这个版配合Home Assistant+Xiaomi Miot用很方便，可以让HA捕获小爱音箱收到的语音触发自动化动作。不必先说“小爱同学，打开小怪”，而且还顺便实现了自己定制启动指令，此外提供给音箱的歌单是一个m3u8格式的playlist文件，用起来也挺好用的。

谢谢两位的奉献！

用HA的话可以考虑用wangrui1573的那个，但HA对资源有点要求高、此外产生的数据量也需要优化调整才能小些……用树莓pi或者N1盒子的还是跑zanjie1999的这个方便，毕竟语音还是省不少事的。

**Comment by zanjie1999** [comment]
> 这次成功了，进来汇报一下。
> 
> 刚刚用20240508的版本在N1盒子的armbian里试过（路由器hosts里加了zyym.ie解析并重启dnsmasq服务），终于可以正确播放了！
> 
> 时隔那么久@zanjie1999还在坚持用爱发电，真的要谢谢你的爱~~ 虽然在作者眼里这个功能可能很小，但真的很实用，对我来说很需要，谢谢！谢谢！谢谢！
> 
> 顺便提个建议，既然每次都要先说“打开小怪”然后发这里那三条命令，能不能加几个简单版的命令别名、比如“随机播放”和“随机播放服务器的音乐”等效？一字不差地说那么长的命令有些违背人性…
> 
> 另外要能给加个“下一首”、以便跳过当前的歌，就更方便了。
> 
> 祝开心、愉快、多爱以供发电！

因为这个本质上是用来做第三方网抑云音乐的，而不是来干这个的，这是他的副业，所以不会做这种简短的（冲突了），并且最简短的已经被小爱音响本身的功能占了
你可以设置米家智能，只要喊智能的名字就能执行批量操作

另外你不说我都没发现有人拷贝了我的代码并删除了我的署名
