### ISSUE TITLE
小爱音箱pro+黑群晖未知故障，不能播放

### ISSUE THREAD

**Issue by sailingsailor** [zanjie1999/httpRandomMusic#4]
设备：小爱音箱pro
服务端：黑群晖J1900 ip:192.168.1.17
windows可以访问，浏览器访问也可以播放。crul和浏览器播放的时候服务端后台有提示。
对小爱说：打开小怪，小爱回复，开始咯
再说别的3条命令都不行了，现象是灯转圈，提示播放失败，请检查网络或换一个试试吧，好菜。服务器没提示。
浏览器访问正常播放op.lan:65533的服务器提示：
192.168.1.66 - - [01/Nov/2023 23:37:07] "GET / HTTP/1.1" 302 -
/
192.168.1.66 - - [01/Nov/2023 23:37:38] "GET / HTTP/1.1" 302 -
/
192.168.1.66 - - [01/Nov/2023 23:40:32] "GET / HTTP/1.1" 302 -
/%E6%96%B0%E6%95%85%E4%BA%8B%E5%AD%A6%E5%A0%82%20-%20%E7%AC%AC2%E9%9B%86%20%E5%8                                                                               9%91%E9%BE%99%E9%B2%81%E5%A4%A7%E7%BE%8E%E7%9A%84%E5%85%AC%E4%B8%BB%E5%9F%8E%E5%                                                                               A0%A1.mp3
/volume2/music/xiaoai/新故事学堂 - 第2集 剑龙鲁大美的公主城堡.mp3
192.168.1.66 - - [01/Nov/2023 23:40:36] "GET /%E6%96%B0%E6%95%85%E4%BA%8B%E5%AD%                                                                               A6%E5%A0%82%20-%20%E7%AC%AC2%E9%9B%86%20%E5%89%91%E9%BE%99%E9%B2%81%E5%A4%A7%E7%                                                                               BE%8E%E7%9A%84%E5%85%AC%E4%B8%BB%E5%9F%8E%E5%A0%A1.mp3 HTTP/1.1" 200 -
/%E6%96%B0%E6%95%85%E4%BA%8B%E5%AD%A6%E5%A0%82%20-%20%E7%AC%AC2%E9%9B%86%20%E5%8                                                                               9%91%E9%BE%99%E9%B2%81%E5%A4%A7%E7%BE%8E%E7%9A%84%E5%85%AC%E4%B8%BB%E5%9F%8E%E5%                                                                               A0%A1.mp3
/volume2/music/xiaoai/新故事学堂 - 第2集 剑龙鲁大美的公主城堡.mp3
192.168.1.66 - - [01/Nov/2023 23:40:36] "GET /%E6%96%B0%E6%95%85%E4%BA%8B%E5%AD%                                                                               A6%E5%A0%82%20-%20%E7%AC%AC2%E9%9B%86%20%E5%89%91%E9%BE%99%E9%B2%81%E5%A4%A7%E7%                                                                               BE%8E%E7%9A%84%E5%85%AC%E4%B8%BB%E5%9F%8E%E5%A0%A1.mp3 HTTP/1.1" 200 -

C:\WINDOWS\system32>nslookup op
服务器:  UnKnown
Address:  fe80::8ac3:97ff:fecb:393d

名称:    op
Address:  192.168.1.17

C:\WINDOWS\system32>nslookup op.lan
服务器:  UnKnown
Address:  fe80::8ac3:97ff:fecb:393d

名称:    op.lan
Address:  192.168.1.17

C:\WINDOWS\system32>curl -v http://op.lan:65533
*   Trying 192.168.1.17:65533...
* Connected to op.lan (192.168.1.17) port 65533 (#0)
> GET / HTTP/1.1
> Host: op.lan:65533
> User-Agent: curl/8.0.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 302 Found
< Server: BaseHTTP/0.6 Python/3.11.4
< Date: Wed, 01 Nov 2023 15:37:07 GMT
< Location: /%E6%96%B0%E6%95%85%E4%BA%8B%E5%AD%A6%E5%A0%82%20-%20%E7%AC%AC3%E9%9B%86%20%E7%89%B9%E6%9A%B4%E9%BE%99%E7%81%AB%E7%81%AB%E9%A3%8E%E5%92%8C%E9%BB%91%E6%9A%97%E9%AD%94%E6%B3%95.mp3
<
* Closing connection 0

**Comment by zanjie1999** [comment]
“播放失败，请检查网络或换一个试试吧” 或者没声就是dns没劫持到
简单的说，就是要在你哪怕手动指定别的tcp或者udp的dns的情况下还能正确解析op.lan，这才算劫持成功
至于怎么弄看你自己的网络环境
