### ISSUE TITLE
您好，装了armbian的N1盒子上可以用吗？

### ISSUE THREAD

**Issue by soskitty** [zanjie1999/httpRandomMusic#6]
您好，感谢您的分享。
我在N1上使用没有成功，我Python版本是3.10.12，hosts按照说明配置了，filedir也修改了，但是一运行就提示错误：
`  File "/home/httpRandomMusic.py", line 100
    <title>httpRandomMusic/httpRandomMusic.py at main · zanjie1999/httpRandomMusic</title>

`
能帮我看看吗，谢谢！

**Comment by zanjie1999** [comment]
我建议你重新下载文件重新编辑，不要删除任何空格，不要输入任何多余的字符，还有你错误根本没贴出来，错误信息就在你复制的内容下面1-3行

**Comment by tasty007** [comment]
> 我建议你重新下载文件重新编辑，不要删除任何空格，不要输入任何多余的字符，还有你错误根本没贴出来，错误信息就在你复制的内容下面1-3行

大神,没有搜索功能放音乐太难受了...
希望能支持搜索播放...只是中文搜索也行,
我看有其他项目小爱音箱可以支持搜索的...

**Comment by zanjie1999** [comment]
> > 我建议你重新下载文件重新编辑，不要删除任何空格，不要输入任何多余的字符，还有你错误根本没贴出来，错误信息就在你复制的内容下面1-3行
> 
> 大神,没有搜索功能放音乐太难受了... 希望能支持搜索播放...只是中文搜索也行, 我看有其他项目小爱音箱可以支持搜索的...

爱用就用，不爱用自己写服务端找小米申请审核上线，都是吃力不讨好的，屁事还多，目前我提供的公益服务随时下线，反正我现在不用了
