### ISSUE TITLE
请问怎么修改路由器hosts

### ISSUE THREAD

**Issue by dreamfly999** [zanjie1999/httpRandomMusic#7]
请问怎么修改路由器hosts，我在服务器上的/etc/hosts文件中添加了一行192.168.101.8 op.lan op ，但是访问http:op.lan:65533显示该网页无法正常运作。

**Comment by dreamfly999** [comment]
刚才改了主机名称，还是不能用

**Comment by zanjie1999** [comment]
百度一下，不会用别用

**Comment by dreamfly999** [comment]
这么傲娇吗，我都不知道怎么回你了

**Comment by dreamfly999** [comment]
有时间我再研究研究吧，感谢你分享的脚本

**Comment by zanjie1999** [comment]
回复你删掉的那条，因为这种问题实在是太基础了，我没必要去百度了复制给你，拒绝服务伸手党，从我做起。
<img width="318" alt="image" src="https://github.com/zanjie1999/httpRandomMusic/assets/16502567/9e5a2298-a865-450f-80fd-4400912c247f">
有邮件的，删了也没用，有这时间在这嘲讽我不如去学习一下怎么调整你的dns劫持

**Comment by dreamfly999** [comment]
最近比较忙，没时间搞了，好像我的路由器也不支持修改hosts，主要还是感谢，网上这种资源还是太少了。原谅我这个小白，只知道跑模型
