### ISSUE TITLE
请教一下，指定有办法自定义吗

### ISSUE THREAD

**Issue by yz-qc** [zanjie1999/httpRandomMusic#8]
请教一下，指定能否自定义，有没有对应的教程额，比如我想 "打开小怪" 是播放儿童歌曲，打开"打开小古"是播放另一个目录的歌曲，还有进入之后的三条指令能否简化，老人可能记不住这么长的指令，多谢大佬

**Comment by zanjie1999** [comment]
米家智能手动任务那么好的功能不用，名字就是触发词
嫌麻烦那你可以别用，另外因为屁事太多也准备下线了，自求多福吧

**Comment by yz-qc** [comment]
额，我就问了一句，不至于火气这么大吧- -。可能被其他人问的烦了，放心，如果你觉得回答麻烦我也不会死缠烂打的。
毕竟你能共享出来已经很不错了，我去研究一下你说的手动任务好了，谢谢

**Comment by zanjie1999** [comment]
新版好像叫批量控制，多添加几个小爱音响自定义指令和延时就可以实现

**Comment by luoyanghero** [comment]
> 新版好像叫批量控制，多添加几个小爱音响自定义指令和延时就可以实现

自定义指令，在米家-通知，显示执行成功。那如何拦截这个指令，映射到本地文件夹？还需要搭建一个http服务端吗，还是就用你现有的脚本就可以了？

**Comment by zanjie1999** [comment]
没有这种功能，想要拦截可以先破解小爱音响系统，然后去试试配合hass
