### ISSUE TITLE
要是不麻烦，可以提供一个docker版本吗？嘿嘿

### ISSUE THREAD

**Issue by hotinewang** [zanjie1999/httpRandomMusic#9]

**Comment by zanjie1999** [comment]
无需docker，标准库就行，直接装上py3就能跑，我不提供容器，但你可以用别人做好的python容器   
以及，建议先弄好dns劫持再来，<b>连做这点事的能力都没有的人，通常都无法完成小爱音响的dns劫持</b>  
另外随时都有可能关闭服务，因为浪费资源，我不用
